_base_: [policy_base]
robot: G1-Hand
left_camera: left_hand_camera
right_camera: right_hand_camera
head_camera: first_person_camera
arm_joints_name: [["left_shoulder_pitch_joint", "left_shoulder_roll_joint", 'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint', 'left_wrist_pitch_joint', 'left_wrist_yaw_joint'],
                  ['right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint']]
gripper_name: [["left_hand_index_0_joint", "left_hand_middle_0_joint","left_hand_thumb_0_joint","left_hand_index_1_joint","left_hand_middle_1_joint","left_hand_thumb_1_joint","left_hand_thumb_2_joint"],
               ["right_hand_index_0_joint","right_hand_middle_0_joint","right_hand_thumb_0_joint","right_hand_index_1_joint","right_hand_middle_1_joint","right_hand_thumb_1_joint","right_hand_thumb_2_joint"]]
