_base_: [rl_base]
task: LiftObj                # Task name
robot: Lerobot-RL                 # Robot type
layout: robocasakitchen-1-8  # Scene layout
num_envs: 1
usd_simplify: true # USD simplify enable
variant: State
enable_cameras: false
